// Generated by CodiumAI

import { Intento } from "./Intento";
import { PalabraIntento } from "./PalabraIntento";

describe("Intento", function () {
  // create an instance of Intento with valid json data
  it("should create an instance of Intento with valid json data", function () {
    const json = {
      _id: "1",
      mazoId: "2",
      acertadas: 3,
      totales: 4,
      palabras: [
        {
          _id: "5",
          natal: "word1",
          traduccion: "translation1",
          acertada: true,
        },
        {
          _id: "6",
          natal: "word2",
          traduccion: "translation2",
          acertada: false,
        },
      ],
      fecha: "2021-01-01",
    };
    const intento = new Intento(json);
    expect(intento._id).toBe("1");
    expect(intento.mazoId).toBe("2");
    expect(intento.acertadas).toBe(3);
    expect(intento.totales).toBe(4);
    expect(intento.palabras.length).toBe(2);
    expect(intento.palabras[0] instanceof PalabraIntento).toBe(true);
    expect(intento.palabras[0]._id).toBe("5");
    expect(intento.palabras[0].natal).toBe("word1");
    expect(intento.palabras[0].traduccion).toBe("translation1");
    expect(intento.palabras[0].acertada).toBe(true);
    expect(intento.palabras[1] instanceof PalabraIntento).toBe(true);
    expect(intento.palabras[1]._id).toBe("6");
    expect(intento.palabras[1].natal).toBe("word2");
    expect(intento.palabras[1].traduccion).toBe("translation2");
    expect(intento.palabras[1].acertada).toBe(false);
    expect(intento.fecha instanceof Date).toBe(true);
    expect(intento.fecha.toISOString()).toBe("2021-01-01T00:00:00.000Z");
  });

  // map an array of json data to an array of Intento instances
  it("should map an array of json data to an array of Intento instances", function () {
    const jsonArray = [
      {
        _id: "1",
        mazoId: "2",
        acertadas: 3,
        totales: 4,
        palabras: [
          {
            _id: "5",
            natal: "word1",
            traduccion: "translation1",
            acertada: true,
          },
          {
            _id: "6",
            natal: "word2",
            traduccion: "translation2",
            acertada: false,
          },
        ],
        fecha: "2021-01-01",
      },
      {
        _id: "7",
        mazoId: "8",
        acertadas: 9,
        totales: 10,
        palabras: [
          {
            _id: "11",
            natal: "word3",
            traduccion: "translation3",
            acertada: true,
          },
          {
            _id: "12",
            natal: "word4",
            traduccion: "translation4",
            acertada: false,
          },
        ],
        fecha: "2021-02-02",
      },
    ];
    const intentos = Intento.mapArray(jsonArray);
    expect(intentos.length).toBe(2);
    expect(intentos[0] instanceof Intento).toBe(true);
    expect(intentos[0]._id).toBe("1");
    expect(intentos[0].mazoId).toBe("2");
    expect(intentos[0].acertadas).toBe(3);
    expect(intentos[0].totales).toBe(4);
    expect(intentos[0].palabras.length).toBe(2);
    expect(intentos[0].palabras[0] instanceof PalabraIntento).toBe(true);
    expect(intentos[0].palabras[0]._id).toBe("5");
    expect(intentos[0].palabras[0].natal).toBe("word1");
    expect(intentos[0].palabras[0].traduccion).toBe("translation1");
    expect(intentos[0].palabras[0].acertada).toBe(true);
    expect(intentos[0].palabras[1] instanceof PalabraIntento).toBe(true);
    expect(intentos[0].palabras[1]._id).toBe("6");
    expect(intentos[0].palabras[1].natal).toBe("word2");
    expect(intentos[0].palabras[1].traduccion).toBe("translation2");
    expect(intentos[0].palabras[1].acertada).toBe(false);
    expect(intentos[0].fecha instanceof Date).toBe(true);
    expect(intentos[0].fecha.toISOString()).toBe("2021-01-01T00:00:00.000Z");
    expect(intentos[1] instanceof Intento).toBe(true);
    expect(intentos[1]._id).toBe("7");
    expect(intentos[1].mazoId).toBe("8");
    expect(intentos[1].acertadas).toBe(9);
    expect(intentos[1].totales).toBe(10);
    expect(intentos[1].palabras.length).toBe(2);
    expect(intentos[1].palabras[0] instanceof PalabraIntento).toBe(true);
    expect(intentos[1].palabras[0]._id).toBe("11");
    expect(intentos[1].palabras[0].natal).toBe("word3");
    expect(intentos[1].palabras[0].traduccion).toBe("translation3");
    expect(intentos[1].palabras[0].acertada).toBe(true);
    expect(intentos[1].palabras[1] instanceof PalabraIntento).toBe(true);
    expect(intentos[1].palabras[1]._id).toBe("12");
    expect(intentos[1].palabras[1].natal).toBe("word4");
    expect(intentos[1].palabras[1].traduccion).toBe("translation4");
    expect(intentos[1].palabras[1].acertada).toBe(false);
    expect(intentos[1].fecha instanceof Date).toBe(true);
    expect(intentos[1].fecha.toISOString()).toBe("2021-02-02T00:00:00.000Z");
  });

  // access the _id, mazoId, fecha, totales, acertadas and palabras properties of an Intento instance
  it("should access the _id, mazoId, fecha, totales, acertadas and palabras properties of an Intento instance", function () {
    const json = {
      _id: "1",
      mazoId: "2",
      acertadas: 3,
      totales: 4,
      palabras: [
        {
          _id: "5",
          natal: "word1",
          traduccion: "translation1",
          acertada: true,
        },
        {
          _id: "6",
          natal: "word2",
          traduccion: "translation2",
          acertada: false,
        },
      ],
      fecha: "2021-01-01",
    };
    const intento = new Intento(json);
    expect(intento._id).toBe("1");
    expect(intento.mazoId).toBe("2");
    expect(intento.acertadas).toBe(3);
    expect(intento.totales).toBe(4);
    expect(intento.palabras.length).toBe(2);
    expect(intento.palabras[0] instanceof PalabraIntento).toBe(true);
    expect(intento.palabras[0]._id).toBe("5");
    expect(intento.palabras[0].natal).toBe("word1");
    expect(intento.palabras[0].traduccion).toBe("translation1");
    expect(intento.palabras[0].acertada).toBe(true);
    expect(intento.palabras[1] instanceof PalabraIntento).toBe(true);
    expect(intento.palabras[1]._id).toBe("6");
    expect(intento.palabras[1].natal).toBe("word2");
    expect(intento.palabras[1].traduccion).toBe("translation2");
    expect(intento.palabras[1].acertada).toBe(false);
    expect(intento.fecha instanceof Date).toBe(true);
    expect(intento.fecha.toISOString()).toBe("2021-01-01T00:00:00.000Z");
  });
});
